version: "3.8"

services:
  productos:
    build:
      context: ./productos
    container_name: productos
    ports:
      - "8080:8080"
    networks:
      - microservicios

  inventario:
    build:
      context: ./inventario
    container_name: inventario
    ports:
      - "8082:8082"
    networks:
      - microservicios

networks:
  microservicios:
    driver: bridge